### ISSUE TITLE
webpage not available

### ISSUE THREAD

**Issue by odarcan** [Sinnefa/Android-Webview-Based-App-Template#3]
Hi Im nuub at this

I just want my own web 2 app instance of my site, without going through tons of other sites

I changed 

`url="https://mysite"`

that alone didnt work it was still showing the assets/index.html

so I moved webView.loadUrl(url);
to outside of the if(savedinstancestate == null){}

now it says
webpage not available 
webpage could not be loaded because
net::ERR_CACHE_MISS

what can be done?

**Comment by odarcan** [comment]
I found the solution after a search

I added `<uses-permission android:name="android.permission.INTERNET"/ >`

to **manifests/AndroidManifest.xml**

under `<manifest ..>`

hope that helps someone!

thanks Sinnefa

**Comment by odarcan** [comment]
Now I have trouble uploading file to my site

**Comment by Sinnefa** [comment]
The app if not meant to handle online websites but offline ones.
