### ISSUE TITLE
POST Files not working

### ISSUE THREAD

**Issue by odarcan** [Sinnefa/Android-Webview-Based-App-Template#4]
POST text upload works

but POST files apparently needs some juju

I tried understanding, but java is not my thing

maybe you can help me out https://stackoverflow.com/questions/69346980/enable-upload-files-in-android-webview-application

**Comment by Sinnefa** [comment]
The app is meant to port basic websites for offline use, to make apps using HTML and JavaScript. You can further implement it yourself to properly handle online sites
